# The name is used to identify the team publicly (e.g. GitHub org team name).
name = "CMU Bulletin"

description = """
Your one-stop shop for everything happening at Carnegie Mellon. Never miss an event on campus again.
"""

# The website and server are not required until the team is ready to deploy.
# Omit the https:// prefix for the website and server.
website = "cmubulletin.com"
server = "your-team-server.com"


# List of repositories owned by the team.
# Note that the owners of the repositories must be ScottyLabs-Labrador.
[[repos]]
name = "CMU-Bulletin"      # As it appears at the end of the GitHub repository URL
description = "Main repo."


# List of membership records by timeframe.
# Note that only the first record will be used for synchronization.
[[membership]]

# The timeframe can be any string, but we suggest using either the year or semester.
# E.g. "2026-2027" or "Spring 2026".
timeframe = "2026-2027"

# List of the GitHub usernames of the leads for this timeframe.
leads = ["ziwei-che"]

# List of members for this timeframe.
[[membership.members]]
github-username = "ziwei-che"

[[membership.members]]
github-username = "angely32"
